CREATE SEQUENCE SEQ_USUARIOS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_USUARIOS (
    USUARIO_ID INTEGER DEFAULT SEQ_USUARIOS.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT 'USER'
);

 CREATE SEQUENCE SEQ_ALERTADESASTRE
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_ALERTADESASTRES (
    ALERTA_DESASTRE_ID INTEGER DEFAULT SEQ_ALERTADESASTRE.NEXTVAL NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    AREA VARCHAR2(100) NOT NULL,
    NIVEL VARCHAR2(20) NOT NULL,
    MENSAGEM VARCHAR2(20),
    DATA DATE NOT NULL
);